"use client";
import React from "react";
import Image from "next/image";
import { BentoGrid, BentoGridItem } from "@/components/ui/bento-grid";
import {
    Code,
    Smartphone,
    Moon,
    Download,
    Eye,
    Layers,
    Database,
    Check
} from "lucide-react";

export default function FeaturesBento() {
    return (
        <section className="py-20" id="features-bento">
            <div className="max-w-7xl w-full mx-auto px-6">
                <h2 className="text-3xl md:text-5xl font-bold text-center text-white mb-12">
                    Everything you need to <br />
                    <span className="bg-clip-text text-transparent bg-linear-to-r from-purple-400 to-pink-600">
                        build faster
                    </span>
                </h2>

                <BentoGrid className="max-w-7xl mx-auto">
                    {items.map((item, i) => (
                        <BentoGridItem
                            key={i}
                            title={item.title}
                            description={item.description}
                            header={item.header}
                            icon={item.icon}
                            className={i === 3 || i === 6 ? "md:col-span-2" : ""}
                        />
                    ))}
                </BentoGrid>
            </div>
        </section>
    );
}



const items = [
    {
        title: "React Components",
        description: "Export clean, functional React components automatically.",
        header: (
            <div className="flex flex-1 w-full h-full min-h-24 rounded-xl bg-linear-to-br from-neutral-900 to-neutral-800 border border-neutral-700 relative overflow-hidden group">
                <Image
                    src="/bento_react_1770356572143.png"
                    alt="React Components"
                    width={400}
                    height={300}
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity duration-300"
                />
            </div>
        ),
        icon: <Layers className="h-4 w-4 text-neutral-500" />,
    },
    {
        title: "Responsive Design",
        description: "Layouts that adapt perfectly to any screen size.",
        header: (
            <div className="flex flex-1 w-full h-full min-h-24 rounded-xl bg-linear-to-br from-neutral-900 to-neutral-800 border border-neutral-700 relative overflow-hidden group">
                <Image
                    src="/bento_responsive_1770356589615.png"
                    alt="Responsive Design"
                    width={400}
                    height={300}
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity duration-300"
                />
            </div>
        ),
        icon: <Smartphone className="h-4 w-4 text-neutral-500" />,
    },
    {
        title: "Theming Support",
        description: "Built-in dark mode and customizable theme tokens.",
        header: (
            <div className="flex flex-1 w-full h-full min-h-24 rounded-xl bg-linear-to-br from-neutral-900 to-neutral-800 border border-neutral-700 relative overflow-hidden group">
                <Image
                    src="/bento_theme_1770356609386.png"
                    alt="Theming Support"
                    width={400}
                    height={300}
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity duration-300"
                />
            </div>
        ),
        icon: <Moon className="h-4 w-4 text-neutral-500" />,
    },
    {
        title: "Instant Code Export",
        description: "Get production-ready code in standard frameworks immediately.",
        header: (
            <div className="flex flex-1 w-full h-full min-h-24 rounded-xl bg-linear-to-br from-neutral-900 to-neutral-800 border border-neutral-700 relative overflow-hidden group">
                <Image
                    src="/bento_export_1770356626592.png"
                    alt="Code Export"
                    width={400}
                    height={300}
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity duration-300"
                />
            </div>
        ),
        icon: <Download className="h-4 w-4 text-neutral-500" />,
    },
    {
        title: "Accessibility Ready",
        description: "Semantically correct HTML generated by default.",
        header: (
            <div className="flex flex-1 w-full h-full min-h-24 rounded-xl bg-linear-to-br from-neutral-900 to-neutral-800 border border-neutral-700 relative overflow-hidden group">
                <Image
                    src="/bento_a11y_1770356647763.png"
                    alt="Accessibility"
                    width={400}
                    height={300}
                    className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity duration-300"
                />
            </div>
        ),
        icon: <Eye className="h-4 w-4 text-neutral-500" />,
    },
];


